# Generated by Django 4.0.4 on 2022-06-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance',
        ),
        migrations.AddField(
            model_name='invoice',
            name='deposit',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Deposit (R)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Invoice', 'Invoice')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 5'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 4'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 1'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 3'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 2'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Total (R)'),
        ),
    ]
