# Generated by Django 4.0.4 on 2022-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0002_remove_invoice_balance_invoice_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_due',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Amount Due (R)'),
        ),
    ]
